[package]
name = "rhiz_tag"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"

[lib]
name = "rhiz_tag"
path = "src/lib.rs"

[[bin]]
name = "hypothesis"
path = "src/bin/hypothesis.rs"
