[package]
name = "rhiz_tag"
version = "0.1.0"
edition = "2021"

[lib]
name = "rhiz_tag"
path = "src/lib.rs"

[[bin]]
name = "hypothesis"
path = "src/bin/hypothesis.rs"

[dependencies]
chrono = { version = "0.4.38", default-features = false }
